/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class ADbleqlCond extends PCond
{
    private TDoubleequals _doubleequals_;

    public ADbleqlCond()
    {
        // Constructor
    }

    public ADbleqlCond(
        @SuppressWarnings("hiding") TDoubleequals _doubleequals_)
    {
        // Constructor
        setDoubleequals(_doubleequals_);

    }

    @Override
    public Object clone()
    {
        return new ADbleqlCond(
            cloneNode(this._doubleequals_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADbleqlCond(this);
    }

    public TDoubleequals getDoubleequals()
    {
        return this._doubleequals_;
    }

    public void setDoubleequals(TDoubleequals node)
    {
        if(this._doubleequals_ != null)
        {
            this._doubleequals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doubleequals_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._doubleequals_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._doubleequals_ == child)
        {
            this._doubleequals_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._doubleequals_ == oldChild)
        {
            setDoubleequals((TDoubleequals) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
