/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class ADecrementStmtexprtail extends PStmtexprtail
{
    private TId _id_;
    private TMinus _minus_;
    private TMinus _dblminus_;

    public ADecrementStmtexprtail()
    {
        // Constructor
    }

    public ADecrementStmtexprtail(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") TMinus _dblminus_)
    {
        // Constructor
        setId(_id_);

        setMinus(_minus_);

        setDblminus(_dblminus_);

    }

    @Override
    public Object clone()
    {
        return new ADecrementStmtexprtail(
            cloneNode(this._id_),
            cloneNode(this._minus_),
            cloneNode(this._dblminus_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecrementStmtexprtail(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public TMinus getDblminus()
    {
        return this._dblminus_;
    }

    public void setDblminus(TMinus node)
    {
        if(this._dblminus_ != null)
        {
            this._dblminus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dblminus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._minus_)
            + toString(this._dblminus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._dblminus_ == child)
        {
            this._dblminus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._dblminus_ == oldChild)
        {
            setDblminus((TMinus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
