/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyVarlist extends PVarlist
{

    public AEmptyVarlist()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyVarlist();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyVarlist(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
