/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import java.util.*;
import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AExptailVarlisttwo extends PVarlisttwo
{
    private PExpr _expr_;
    private final LinkedList<PVarlisttwotail> _varlisttwotail_ = new LinkedList<PVarlisttwotail>();

    public AExptailVarlisttwo()
    {
        // Constructor
    }

    public AExptailVarlisttwo(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") List<?> _varlisttwotail_)
    {
        // Constructor
        setExpr(_expr_);

        setVarlisttwotail(_varlisttwotail_);

    }

    @Override
    public Object clone()
    {
        return new AExptailVarlisttwo(
            cloneNode(this._expr_),
            cloneList(this._varlisttwotail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExptailVarlisttwo(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public LinkedList<PVarlisttwotail> getVarlisttwotail()
    {
        return this._varlisttwotail_;
    }

    public void setVarlisttwotail(List<?> list)
    {
        for(PVarlisttwotail e : this._varlisttwotail_)
        {
            e.parent(null);
        }
        this._varlisttwotail_.clear();

        for(Object obj_e : list)
        {
            PVarlisttwotail e = (PVarlisttwotail) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._varlisttwotail_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._varlisttwotail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._varlisttwotail_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        for(ListIterator<PVarlisttwotail> i = this._varlisttwotail_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVarlisttwotail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
