/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AGteqlCond extends PCond
{
    private TGtequals _gtequals_;

    public AGteqlCond()
    {
        // Constructor
    }

    public AGteqlCond(
        @SuppressWarnings("hiding") TGtequals _gtequals_)
    {
        // Constructor
        setGtequals(_gtequals_);

    }

    @Override
    public Object clone()
    {
        return new AGteqlCond(
            cloneNode(this._gtequals_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGteqlCond(this);
    }

    public TGtequals getGtequals()
    {
        return this._gtequals_;
    }

    public void setGtequals(TGtequals node)
    {
        if(this._gtequals_ != null)
        {
            this._gtequals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gtequals_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._gtequals_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._gtequals_ == child)
        {
            this._gtequals_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._gtequals_ == oldChild)
        {
            setGtequals((TGtequals) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
