/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class ALteqlCond extends PCond
{
    private TLtequals _ltequals_;

    public ALteqlCond()
    {
        // Constructor
    }

    public ALteqlCond(
        @SuppressWarnings("hiding") TLtequals _ltequals_)
    {
        // Constructor
        setLtequals(_ltequals_);

    }

    @Override
    public Object clone()
    {
        return new ALteqlCond(
            cloneNode(this._ltequals_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALteqlCond(this);
    }

    public TLtequals getLtequals()
    {
        return this._ltequals_;
    }

    public void setLtequals(TLtequals node)
    {
        if(this._ltequals_ != null)
        {
            this._ltequals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ltequals_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ltequals_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ltequals_ == child)
        {
            this._ltequals_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ltequals_ == oldChild)
        {
            setLtequals((TLtequals) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
