/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AMethodstmt extends PMethodstmt
{
    private PMethodexpr _methodexpr_;

    public AMethodstmt()
    {
        // Constructor
    }

    public AMethodstmt(
        @SuppressWarnings("hiding") PMethodexpr _methodexpr_)
    {
        // Constructor
        setMethodexpr(_methodexpr_);

    }

    @Override
    public Object clone()
    {
        return new AMethodstmt(
            cloneNode(this._methodexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodstmt(this);
    }

    public PMethodexpr getMethodexpr()
    {
        return this._methodexpr_;
    }

    public void setMethodexpr(PMethodexpr node)
    {
        if(this._methodexpr_ != null)
        {
            this._methodexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._methodexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._methodexpr_ == child)
        {
            this._methodexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._methodexpr_ == oldChild)
        {
            setMethodexpr((PMethodexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
