/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AMorecases extends PMorecases
{
    private TCase _case_;
    private TLparen _lparen_;
    private TIntnum _intnum_;
    private TRparen _rparen_;
    private TColon _colon_;
    private PStmtseq _stmtseq_;
    private PBreakpart _breakpart_;

    public AMorecases()
    {
        // Constructor
    }

    public AMorecases(
        @SuppressWarnings("hiding") TCase _case_,
        @SuppressWarnings("hiding") TLparen _lparen_,
        @SuppressWarnings("hiding") TIntnum _intnum_,
        @SuppressWarnings("hiding") TRparen _rparen_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PStmtseq _stmtseq_,
        @SuppressWarnings("hiding") PBreakpart _breakpart_)
    {
        // Constructor
        setCase(_case_);

        setLparen(_lparen_);

        setIntnum(_intnum_);

        setRparen(_rparen_);

        setColon(_colon_);

        setStmtseq(_stmtseq_);

        setBreakpart(_breakpart_);

    }

    @Override
    public Object clone()
    {
        return new AMorecases(
            cloneNode(this._case_),
            cloneNode(this._lparen_),
            cloneNode(this._intnum_),
            cloneNode(this._rparen_),
            cloneNode(this._colon_),
            cloneNode(this._stmtseq_),
            cloneNode(this._breakpart_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMorecases(this);
    }

    public TCase getCase()
    {
        return this._case_;
    }

    public void setCase(TCase node)
    {
        if(this._case_ != null)
        {
            this._case_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._case_ = node;
    }

    public TLparen getLparen()
    {
        return this._lparen_;
    }

    public void setLparen(TLparen node)
    {
        if(this._lparen_ != null)
        {
            this._lparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lparen_ = node;
    }

    public TIntnum getIntnum()
    {
        return this._intnum_;
    }

    public void setIntnum(TIntnum node)
    {
        if(this._intnum_ != null)
        {
            this._intnum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intnum_ = node;
    }

    public TRparen getRparen()
    {
        return this._rparen_;
    }

    public void setRparen(TRparen node)
    {
        if(this._rparen_ != null)
        {
            this._rparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rparen_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PStmtseq getStmtseq()
    {
        return this._stmtseq_;
    }

    public void setStmtseq(PStmtseq node)
    {
        if(this._stmtseq_ != null)
        {
            this._stmtseq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmtseq_ = node;
    }

    public PBreakpart getBreakpart()
    {
        return this._breakpart_;
    }

    public void setBreakpart(PBreakpart node)
    {
        if(this._breakpart_ != null)
        {
            this._breakpart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._breakpart_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._case_)
            + toString(this._lparen_)
            + toString(this._intnum_)
            + toString(this._rparen_)
            + toString(this._colon_)
            + toString(this._stmtseq_)
            + toString(this._breakpart_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._case_ == child)
        {
            this._case_ = null;
            return;
        }

        if(this._lparen_ == child)
        {
            this._lparen_ = null;
            return;
        }

        if(this._intnum_ == child)
        {
            this._intnum_ = null;
            return;
        }

        if(this._rparen_ == child)
        {
            this._rparen_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._stmtseq_ == child)
        {
            this._stmtseq_ = null;
            return;
        }

        if(this._breakpart_ == child)
        {
            this._breakpart_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._case_ == oldChild)
        {
            setCase((TCase) newChild);
            return;
        }

        if(this._lparen_ == oldChild)
        {
            setLparen((TLparen) newChild);
            return;
        }

        if(this._intnum_ == oldChild)
        {
            setIntnum((TIntnum) newChild);
            return;
        }

        if(this._rparen_ == oldChild)
        {
            setRparen((TRparen) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._stmtseq_ == oldChild)
        {
            setStmtseq((PStmtseq) newChild);
            return;
        }

        if(this._breakpart_ == oldChild)
        {
            setBreakpart((PBreakpart) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
