/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AMorestatementsMethodstmtseqs extends PMethodstmtseqs
{
    private PMethodstmtseqs _methodstmtseqs_;
    private PMethodstmtseq _methodstmtseq_;

    public AMorestatementsMethodstmtseqs()
    {
        // Constructor
    }

    public AMorestatementsMethodstmtseqs(
        @SuppressWarnings("hiding") PMethodstmtseqs _methodstmtseqs_,
        @SuppressWarnings("hiding") PMethodstmtseq _methodstmtseq_)
    {
        // Constructor
        setMethodstmtseqs(_methodstmtseqs_);

        setMethodstmtseq(_methodstmtseq_);

    }

    @Override
    public Object clone()
    {
        return new AMorestatementsMethodstmtseqs(
            cloneNode(this._methodstmtseqs_),
            cloneNode(this._methodstmtseq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMorestatementsMethodstmtseqs(this);
    }

    public PMethodstmtseqs getMethodstmtseqs()
    {
        return this._methodstmtseqs_;
    }

    public void setMethodstmtseqs(PMethodstmtseqs node)
    {
        if(this._methodstmtseqs_ != null)
        {
            this._methodstmtseqs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodstmtseqs_ = node;
    }

    public PMethodstmtseq getMethodstmtseq()
    {
        return this._methodstmtseq_;
    }

    public void setMethodstmtseq(PMethodstmtseq node)
    {
        if(this._methodstmtseq_ != null)
        {
            this._methodstmtseq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodstmtseq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._methodstmtseqs_)
            + toString(this._methodstmtseq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._methodstmtseqs_ == child)
        {
            this._methodstmtseqs_ = null;
            return;
        }

        if(this._methodstmtseq_ == child)
        {
            this._methodstmtseq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._methodstmtseqs_ == oldChild)
        {
            setMethodstmtseqs((PMethodstmtseqs) newChild);
            return;
        }

        if(this._methodstmtseq_ == oldChild)
        {
            setMethodstmtseq((PMethodstmtseq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
