/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class ANeqlCond extends PCond
{
    private TNotequals _notequals_;

    public ANeqlCond()
    {
        // Constructor
    }

    public ANeqlCond(
        @SuppressWarnings("hiding") TNotequals _notequals_)
    {
        // Constructor
        setNotequals(_notequals_);

    }

    @Override
    public Object clone()
    {
        return new ANeqlCond(
            cloneNode(this._notequals_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANeqlCond(this);
    }

    public TNotequals getNotequals()
    {
        return this._notequals_;
    }

    public void setNotequals(TNotequals node)
    {
        if(this._notequals_ != null)
        {
            this._notequals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notequals_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._notequals_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._notequals_ == child)
        {
            this._notequals_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._notequals_ == oldChild)
        {
            setNotequals((TNotequals) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
