/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class ARealFactor extends PFactor
{
    private TRealnum _realnum_;

    public ARealFactor()
    {
        // Constructor
    }

    public ARealFactor(
        @SuppressWarnings("hiding") TRealnum _realnum_)
    {
        // Constructor
        setRealnum(_realnum_);

    }

    @Override
    public Object clone()
    {
        return new ARealFactor(
            cloneNode(this._realnum_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARealFactor(this);
    }

    public TRealnum getRealnum()
    {
        return this._realnum_;
    }

    public void setRealnum(TRealnum node)
    {
        if(this._realnum_ != null)
        {
            this._realnum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._realnum_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._realnum_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._realnum_ == child)
        {
            this._realnum_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._realnum_ == oldChild)
        {
            setRealnum((TRealnum) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
