/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class TBreak extends Token
{
    public TBreak()
    {
        super.setText("BREAK");
    }

    public TBreak(int line, int pos)
    {
        super.setText("BREAK");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBreak(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBreak(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBreak text.");
    }
}
