/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class TDblquote extends Token
{
    public TDblquote()
    {
        super.setText("\"");
    }

    public TDblquote(int line, int pos)
    {
        super.setText("\"");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDblquote(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDblquote(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDblquote text.");
    }
}
