/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class TPut extends Token
{
    public TPut()
    {
        super.setText("PUT");
    }

    public TPut(int line, int pos)
    {
        super.setText("PUT");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPut(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPut(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPut text.");
    }
}
