/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class TReal extends Token
{
    public TReal()
    {
        super.setText("REAL");
    }

    public TReal(int line, int pos)
    {
        super.setText("REAL");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReal(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReal(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReal text.");
    }
}
