/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.parser;

import Project5.node.*;
import Project5.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTBegin(@SuppressWarnings("unused") TBegin node)
    {
        this.index = 0;
    }

    @Override
    public void caseTEnd(@SuppressWarnings("unused") TEnd node)
    {
        this.index = 1;
    }

    @Override
    public void caseTClas(@SuppressWarnings("unused") TClas node)
    {
        this.index = 2;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 3;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 4;
    }

    @Override
    public void caseTThen(@SuppressWarnings("unused") TThen node)
    {
        this.index = 5;
    }

    @Override
    public void caseTNew(@SuppressWarnings("unused") TNew node)
    {
        this.index = 6;
    }

    @Override
    public void caseTReturn(@SuppressWarnings("unused") TReturn node)
    {
        this.index = 7;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 8;
    }

    @Override
    public void caseTReal(@SuppressWarnings("unused") TReal node)
    {
        this.index = 9;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 10;
    }

    @Override
    public void caseTBool(@SuppressWarnings("unused") TBool node)
    {
        this.index = 11;
    }

    @Override
    public void caseTVoid(@SuppressWarnings("unused") TVoid node)
    {
        this.index = 12;
    }

    @Override
    public void caseTSwitch(@SuppressWarnings("unused") TSwitch node)
    {
        this.index = 13;
    }

    @Override
    public void caseTCase(@SuppressWarnings("unused") TCase node)
    {
        this.index = 14;
    }

    @Override
    public void caseTDefault(@SuppressWarnings("unused") TDefault node)
    {
        this.index = 15;
    }

    @Override
    public void caseTBreak(@SuppressWarnings("unused") TBreak node)
    {
        this.index = 16;
    }

    @Override
    public void caseTPut(@SuppressWarnings("unused") TPut node)
    {
        this.index = 17;
    }

    @Override
    public void caseTTrue(@SuppressWarnings("unused") TTrue node)
    {
        this.index = 18;
    }

    @Override
    public void caseTFalse(@SuppressWarnings("unused") TFalse node)
    {
        this.index = 19;
    }

    @Override
    public void caseTWhile(@SuppressWarnings("unused") TWhile node)
    {
        this.index = 20;
    }

    @Override
    public void caseTFor(@SuppressWarnings("unused") TFor node)
    {
        this.index = 21;
    }

    @Override
    public void caseTGet(@SuppressWarnings("unused") TGet node)
    {
        this.index = 22;
    }

    @Override
    public void caseTUnderscore(@SuppressWarnings("unused") TUnderscore node)
    {
        this.index = 23;
    }

    @Override
    public void caseTRparen(@SuppressWarnings("unused") TRparen node)
    {
        this.index = 24;
    }

    @Override
    public void caseTLparen(@SuppressWarnings("unused") TLparen node)
    {
        this.index = 25;
    }

    @Override
    public void caseTRcurly(@SuppressWarnings("unused") TRcurly node)
    {
        this.index = 26;
    }

    @Override
    public void caseTLcurly(@SuppressWarnings("unused") TLcurly node)
    {
        this.index = 27;
    }

    @Override
    public void caseTRbrace(@SuppressWarnings("unused") TRbrace node)
    {
        this.index = 28;
    }

    @Override
    public void caseTLbrace(@SuppressWarnings("unused") TLbrace node)
    {
        this.index = 29;
    }

    @Override
    public void caseTGt(@SuppressWarnings("unused") TGt node)
    {
        this.index = 30;
    }

    @Override
    public void caseTLt(@SuppressWarnings("unused") TLt node)
    {
        this.index = 31;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 32;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 33;
    }

    @Override
    public void caseTTimes(@SuppressWarnings("unused") TTimes node)
    {
        this.index = 34;
    }

    @Override
    public void caseTDivide(@SuppressWarnings("unused") TDivide node)
    {
        this.index = 35;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 36;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 37;
    }

    @Override
    public void caseTEquals(@SuppressWarnings("unused") TEquals node)
    {
        this.index = 38;
    }

    @Override
    public void caseTExc(@SuppressWarnings("unused") TExc node)
    {
        this.index = 39;
    }

    @Override
    public void caseTPeriod(@SuppressWarnings("unused") TPeriod node)
    {
        this.index = 40;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 41;
    }

    @Override
    public void caseTDblquote(@SuppressWarnings("unused") TDblquote node)
    {
        this.index = 42;
    }

    @Override
    public void caseTSubset(@SuppressWarnings("unused") TSubset node)
    {
        this.index = 43;
    }

    @Override
    public void caseTStringlit(@SuppressWarnings("unused") TStringlit node)
    {
        this.index = 44;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 45;
    }

    @Override
    public void caseTRealnum(@SuppressWarnings("unused") TRealnum node)
    {
        this.index = 46;
    }

    @Override
    public void caseTIntnum(@SuppressWarnings("unused") TIntnum node)
    {
        this.index = 47;
    }

    @Override
    public void caseTDoubleequals(@SuppressWarnings("unused") TDoubleequals node)
    {
        this.index = 48;
    }

    @Override
    public void caseTNotequals(@SuppressWarnings("unused") TNotequals node)
    {
        this.index = 49;
    }

    @Override
    public void caseTGtequals(@SuppressWarnings("unused") TGtequals node)
    {
        this.index = 50;
    }

    @Override
    public void caseTLtequals(@SuppressWarnings("unused") TLtequals node)
    {
        this.index = 51;
    }

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 52;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 53;
    }
}
